export const BACKMAINFROMNEWACCOUNT = 'backMainFromNewAccount'
export const ADDACCOUNTTOLIST = 'addAccountToList'
export const EDITACCOUNTINLIST = 'editAccountInList'
export const REMOVEACCOUNTROMLIST = 'removeAccountFromList'
export const ADDOPERATIONTOLIST = 'AddOperationToList'
export const SELECTTYPEOPERATION = 'selectTypeOperation'

// export const SERVERURL = 'https://guarded-sea-48553.herokuapp.com/'
// export const SERVERURL = 'http://127.0.0.1:8000/'
export const SERVERURL = 'http://127.0.0.1:5000/'